<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
        <PackageReference Include="Apache.Avro" Version="1.12.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NStalling.Avro.DependencyInjection\NStalling.Avro.DependencyInjection.csproj" />
        <ProjectReference Include="..\NStalling.Avro\NStalling.Avro.csproj"/>
        <ProjectReference Include="..\NStalling.Avro.Samples\EventEnvelope\EventEnvelope.csproj"/>
        <ProjectReference Include="..\NStalling.Avro.Samples\Annotations\Annotations.csproj"/>
        <ProjectReference Include="..\NStalling.Avro.Samples\DependencyInjection\DependencyInjection.csproj"/>
        <ProjectReference Include="..\NStalling.Avro.Samples\TypeResolver\TypeResolver.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>