<Project>

  <PropertyGroup>
    <Authors>Nathaniel Nielsen</Authors>
    <Copyright>Copyright © Nathaniel Nielsen</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/NateIsStalling/NStalling.Avro</PackageProjectUrl>
    <RepositoryUrl>https://github.com/NateIsStalling/NStalling.Avro</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
  </ItemGroup>

</Project>
